project:
  type: website
  output-dir: docs
  resources:
    - record-form.js
    - view-data.js
    - totals.js

website:
  title: "Carica Record"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Inserisci Dati
        icon: house-fill
      - href: view.qmd
        text: Visualizza Dati
        icon: table
      - href: totals.qmd
        text: Totali per Persona
        icon: calculator

format:
  html:
    theme: 
      - cosmo
    toc: false
    page-layout: full