project:
  type: website
  output-dir: docs
  resources:
    - record-form.js

website:
  title: "Carica Record"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
        icon: house-fill

format:
  html:
    theme: 
      - cosmo
    toc: false
    page-layout: full

    